# Generated by Django 4.2.16 on 2025-09-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('resources', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_outlook', models.TextField(blank=True)),
                ('education_path', models.JSONField(default=list)),
                ('career_steps', models.JSONField(default=list)),
                ('top_companies', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
