# Generated by Django 4.2.16 on 2025-09-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('career_title', models.CharField(max_length=200)),
                ('match_score', models.FloatField()),
                ('reasoning', models.JSONField(default=list)),
                ('market_outlook', models.JSONField(default=dict)),
                ('skill_gaps', models.JSONField(default=list)),
                ('learning_path', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('demand_score', models.FloatField()),
                ('avg_salary', models.IntegerField()),
                ('growth_rate', models.FloatField()),
                ('location', models.CharField(default='Global', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('personality_type', models.CharField(choices=[('analyst', 'Analyst'), ('diplomat', 'Diplomat'), ('sentinel', 'Sentinel'), ('explorer', 'Explorer')], max_length=20)),
                ('traits', models.JSONField(default=dict)),
                ('career_preferences', models.JSONField(default=list)),
                ('work_style', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
